### PR TITLE
Initial minimal data for Finland

### PR DESCRIPTION
**Pull request by tml1024**
No idea if there are syntax or logic errors, just want a review...

### CODE REVIEW

**Comment by tml1024** [comment]
By the way, from the kilometre points from https://avoinapi.vaylapilvi.fi/vaylatiedot/ows?service=wfs&request=getFeature&typeName=ratatiedot:track_kilometers&outputFormat=kml I used a Python script to generate for instance this .osm file, for the main railway ("route_name" 003) from Helsinki to Seinäjoki. I.e. one segment per kilometre point, so not very smooth. They also have data for the actual railway tracks that contains a lot of more points and thus is smoother, but that would then need some filtering to combine double tracks into just one line. Plus stations have lots of tracks of course.

[003.osm.txt](https://github.com/user-attachments/files/17963547/003.osm.txt)

**Comment by tml1024** [comment]
Python script
[track_kilometers_to_osm.py.txt](https://github.com/user-attachments/files/17963562/track_kilometers_to_osm.py.txt)

I don't have much experience in Python, and it shows...

**Comment by partim** [comment]
Thank you for the PR!

The [raildata](https://github.com/railwayhistory/raildata) repository has a syntax checker that you can install and run locally (I’ll add instructions to the README.)

It currently says:

```
18 errors.
./facts/fi/company.yaml::6:0: unexpected key source
./facts/fi/company.yaml::24:0: unexpected key source
./facts/fi/company.yaml::36:8: duplicate mapping key
./facts/fi/company.yaml::43:0: unexpected key source
./facts/fi/company.yaml::60:0: unexpected key source
./facts/fi/company.yaml::73:0: unexpected key source
./facts/fi/company.yaml::92:0: unexpected key source
./facts/fi/company.yaml::106:0: unexpected key source
./facts/fi/company.yaml::118:0: unexpected key source
./facts/fi/company.yaml::132:0: unexpected key source
./facts/fi/company.yaml::133:0: unexpected key name
./facts/fi/company.yaml::143:0: unexpected key source
./facts/fi/company.yaml::144:0: unexpected key short_name
./facts/fi/company.yaml::145:0: unexpected key name
./facts/fi/company.yaml::155:0: unexpected key source
./facts/fi/company.yaml::156:0: unexpected key name
./facts/fi/company.yaml::169:0: unexpected key source
./facts/fi/company.yaml::170:0: unexpected key name
```

**Comment by partim** [comment]
For the geographical data, I generally create those files manually with JOSM. It is less work than you’d think and – your mileage, of course, may vary – quite enjoyable.

That said, it looks like we could use those route number as the line keys? Which would leave the question whether the Helsinki – Seinäjoki line should be `line.fi.003` or `line.fi.3`.

**Comment by tml1024** [comment]
Nah, sorry, JOSM did not make very keen to use it more when I tried… seemed very old fashioned and awkward. (Says he who uses Emacs for his text editing…) Is there any more modern tool?

**Comment by partim** [comment]
I am not aware of anything else. I am actually quite happy with JOSM. It does its job fairly well. Is it perhaps just the awful default Java UI theme? You can change that and make it look more GTK or Windows.

**Comment by partim** [comment]
That said: I am happy to clean up those path files if you prefer to just work with the generated ones.

**Comment by tml1024** [comment]
How should one encode the situation where an entity splits up into several? Like when the previous Finnnish State Railways, a government agency, split into separate infrastructure owner (still a government agency) and operator (a state-owned company).

**Comment by tml1024** [comment]
> For the geographical data, I generally create those files manually with JOSM. It is less work than you’d think and – your mileage, of course, may vary – quite enjoyable.

> That said, it looks like we could use those route number as the line keys? Which would leave the question whether the Helsinki – Seinäjoki line should be line.fi.003 or line.fi.3.

My current understanding is that the "003" format is the official one. At least in the track_kilometers dataset, it is called "route_name". But not all the lines have purely numerical identifier, there are some (maybe just short industrial or harbour branch lines) with identifiers like "AJO 028", "HY 323", and even "003410 PRL". But in the "locationtracks" dataset there is also something called "accounting_route_number" which are different numbers.

**Comment by partim** [comment]
> How should one encode the situation where an entity splits up into several? Like when the previous Finnnish State Railways, a government agency, split into separate infrastructure owner (still a government agency) and operator (a state-owned company).

So far I just treated this case as two new entities opening and the old one closing. If necessary, the `property` attribute can be used to shift assets to a new entity without having to add a million new events.

**Comment by partim** [comment]
Apologies for messing up your comment. Wanted to quote, ended up editing.

**Comment by partim** [comment]
> But in the "locationtracks" dataset there is also something called "accounting_route_number" which are different numbers.

The accounting number also appears on the [offical map](https://vayla.fi/documents/25230764/47264414/Rataverkko_01012021.pdf) and seem to be for shorter segments.

**Comment by tml1024** [comment]
When an entity changes name but nothing else changes, should that be a separate event with just date: and name:, or should there be a separate entity as the successor?

**Comment by tml1024** [comment]
Another question: What does the "operator" of a line mean? Many countries have dozens of freight operators running trains, should they be listed for all lines, hardly? Or just for the lines where they actually happen to run trains at the moment, but that will be very ephemeral information?

**Comment by partim** [comment]
Operator is a misnomer – what it really means is the infrastructure manager but I didn’t know that was the term at the time. Perhaps it should be changed to `manager` (and `operator` left as an obsolete alias so we don’t have to change all its occurrences.)

**Comment by partim** [comment]
Minor esthetic question: Is it possible to keep the Emacs mode line out of the individual files? Or, if that’s a pain, can they be at the bottom?

**Comment by partim** [comment]
One more thing: The country line lists are now in `research/<country-code>/lines.txt`.

**Comment by tml1024** [comment]
> Minor esthetic question: Is it possible to keep the Emacs mode line out of the individual files? Or, if that’s a pain, can they be at the bottom?

It can be towards the end of the file, too, but sadly then multiple lines are needed: https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html

You can of course keep personal settings (arbitrary long code in Elisp) that cause Emacs to use whatever tweaks you like depending on file name and/or location, but they are per-user, and for files at least nominally intended to be collaborated on by potentially several people, each one would then need to do it separately. (I.e. there is no way to have a settings file in the same directory tree that Emacs would use, as far as I know.)

**Comment by tml1024** [comment]
> Operator is a misnomer

So the intent is that train operators shouldn't be displayed anywhere, what this is about is the infrastructure? Makes sense. (I will then remove the few Finnish operators in this PR.)

**Comment by partim** [comment]
I’m undecided about train operators. This gets fairly close to including timetable data and maybe that should be in a separate project – if only because it probably requires a different data model.

There’s also the issue that infrastructure manager and train operator were identical for most of history (and still often are). Maybe this should be reflected somehow? Perhaps as an attribute on the managing organization?

**Comment by partim** [comment]
I suppose we can merge the PR.

**Review by partim — APPROVED** [review]

**Comment by tml1024** [comment]
Hmm, it didn't get merged automatically upon approval?

**Comment by partim** [comment]
Nope, but I shall push the button now …

**Pull request merged**
